"""initial

Revision ID: afe5af42fb8c
Revises:
Create Date: 2026-03-08 12:48:55.117340

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afe5af42fb8c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genre",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "source",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("scraper_key", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "vinyl",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("artist", sa.String(length=500), nullable=False),
        sa.Column("label", sa.String(length=500), nullable=True),
        sa.Column("catalog_number", sa.String(length=200), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("condition", sa.String(length=50), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("musicbrainz_id", sa.String(length=36), nullable=True),
        sa.Column("release_group_id", sa.String(length=36), nullable=True),
        sa.Column("youtube_url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_vinyl_artist_title",
        "vinyl",
        [sa.literal_column("lower(artist)"), sa.literal_column("lower(title)")],
        unique=False,
    )
    op.create_index(
        "ix_vinyl_musicbrainz_id",
        "vinyl",
        ["musicbrainz_id"],
        unique=True,
        postgresql_where=sa.text("musicbrainz_id IS NOT NULL"),
    )
    op.create_table(
        "tracklist",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vinyl_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("duration", sa.String(length=20), nullable=True),
        sa.Column("youtube_url", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["vinyl_id"], ["vinyl.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vinyl_genre",
        sa.Column("vinyl_id", sa.UUID(), nullable=True),
        sa.Column("genre_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["genre_id"], ["genre.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vinyl_id"], ["vinyl.id"], ondelete="CASCADE"),
    )
    op.create_table(
        "vinyl_source",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vinyl_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("external_url", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("in_stock", sa.Boolean(), nullable=False),
        sa.Column(
            "scraped_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vinyl_id"], ["vinyl.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_vinyl_source_vinyl_source",
        "vinyl_source",
        ["vinyl_id", "source_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vinyl_source_vinyl_source", table_name="vinyl_source")
    op.drop_table("vinyl_source")
    op.drop_table("vinyl_genre")
    op.drop_table("tracklist")
    op.drop_index(
        "ix_vinyl_musicbrainz_id",
        table_name="vinyl",
        postgresql_where=sa.text("musicbrainz_id IS NOT NULL"),
    )
    op.drop_index("ix_vinyl_artist_title", table_name="vinyl")
    op.drop_table("vinyl")
    op.drop_table("source")
    op.drop_table("genre")
    # ### end Alembic commands ###
