"""widen_track_position_column

Revision ID: f207bff6ac77
Revises: afe5af42fb8c
Create Date: 2026-03-08 14:19:49.410194

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f207bff6ac77"
down_revision: Union[str, None] = "afe5af42fb8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tracklist",
        "position",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tracklist",
        "position",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
